#!/bin/bash
set -eu

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

if [ $(echo $DOCKER_TAG | grep ID | grep 18.04) ]; then
    ROS_DISTRO="melodic";
else
    ROS_DISTRO="kinetic";
fi
echo "##################################" && echo $DOCKER_TAG $$ echo $ROS_DISTRO && echo "##########################"
docker build --build-arg BASE_TAG=$DOCKER_TAG --build-arg ROS_DISTRO=$ROS_DISTRO $DOCKERFILE_PATH_ARG -t $IMAGE_NAME .
